site_name: MkDocs Test
site_url: https://www.raynamharris.com/MkDocs-demo-1
repo_name: MkDocs-demo-1
repo_url: https://github.com/raynamharris/MkDocs-demo-1
edit_uri: ""

#extra_css: css/custom.css

copyright: 'Copyright &copy; 2022 <a href="http://ivory.idyll.org/lab/">Lab for Data Intensive Biology</a> at UC Davis'

# change directory names here
docs_dir: docs
site_dir: site

theme:
  name: material
  
  # pretty colors! see https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
  palette:
    primary: 'green'
    accent: 'purple'
  
  # fun logos! see https://material.io/icons/
  icon:
    logo: material/dns

  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  
  features:
    - instant

markdown_extensions:
    - fontawesome_markdown
